Repository alibaba/FederatedScope, pull requests merged in 2022-04, with the labels that each got.

#6 modify README
  README.md
Labels: documentation

#8 improved the environments set-up guidance
  README.md
  enviroment/docker_files/README.md
  enviroment/docker_files/federatedscope-jupyterhub/Dockerfile
  enviroment/docker_files/federatedscope-jupyterhub/fix-permissions
  enviroment/docker_files/federatedscope-jupyterhub/jupyter_server_config.py
  enviroment/docker_files/federatedscope-jupyterhub/start-notebook.sh
  enviroment/docker_files/federatedscope-jupyterhub/start-singleuser.sh
  enviroment/docker_files/federatedscope-jupyterhub/start.sh
  enviroment/docker_files/federatedscope-torch1.10-application.Dockerfile
  enviroment/docker_files/federatedscope-torch1.10.Dockerfile
  enviroment/docker_files/federatedscope-torch1.8.Dockerfile
  enviroment/requirements-torch1.10-application.txt
  enviroment/requirements-torch1.10.txt
  setup.py
Labels: documentation

#7 updated auto-doc component according to the latest changes
  doc/source/attack.rst
  doc/source/cSBM_dataset.rst
  doc/source/contributors.rst
  doc/source/core.rst
  doc/source/cv.rst
  doc/source/examples.rst
  doc/source/gfl.rst
  doc/source/index.rst
  doc/source/installation.rst
  doc/source/leaf.rst
  doc/source/nlp.rst
  doc/source/trainer.rst
Labels: documentation

#11 [Feature] Add dropout and log training metric.
  README.md
  federatedscope/core/auxiliaries/criterion_builder.py
  federatedscope/core/configs/cfg_evaluation.py
  federatedscope/core/trainers/trainer.py
  federatedscope/core/worker/client.py
  federatedscope/core/worker/server.py
  federatedscope/cv/baseline/fedavg_convnet2_on_celeba.yaml
  federatedscope/cv/baseline/fedavg_convnet2_on_femnist.yaml
  federatedscope/cv/baseline/fedbn_convnet2_on_femnist.yaml
  federatedscope/cv/model/cnn.py
  federatedscope/cv/model/model_builder.py
  federatedscope/nlp/baseline/fedavg_lr_on_twitter.yaml
  federatedscope/nlp/baseline/fedavg_lstm_on_shakespeare.yaml
  federatedscope/nlp/baseline/fedavg_lstm_on_subreddit.yaml
  federatedscope/nlp/model/model_builder.py
  federatedscope/nlp/model/rnn.py
Labels: Feature

#13 enabled the log file name valid in windows environment
  federatedscope/core/auxiliaries/utils.py
Labels: enhancement

#15 update readme
  README.md
Labels: documentation

#14 added a demo for black-box optimization
  demo/bbo.py
  enviroment/requirements-torch1.8-application.txt
  federatedscope/main.py
Labels: Feature

#17 [Bugfix] fixed the invalid logger set-up if the logging is used before we call setup_logger
  federatedscope/core/auxiliaries/utils.py
  federatedscope/core/configs/cfg_fl_setting.py
Labels: bug

#20 Change source of `download_url` from our own and fix `README`
  README.md
  federatedscope/core/auxiliaries/utils.py
  federatedscope/cv/dataset/leaf.py
  federatedscope/cv/dataset/leaf_cv.py
  federatedscope/nlp/dataset/leaf_nlp.py
Labels: documentation, enhancement

#26 add logo
  README.md
Labels: documentation

#30 Fix the logger usage
  demo/bbo.py
  demo/hpbandster/rs.py
  federatedscope/__init__.py
  federatedscope/attack/auxiliary/utils.py
  federatedscope/attack/privacy_attacks/reconstruction_opt.py
  federatedscope/attack/trainer/MIA_invert_gradient_trainer.py
  federatedscope/attack/worker_as_attacker/active_client.py
  federatedscope/autotune/algos.py
  federatedscope/config.py
  federatedscope/core/auxiliaries/aggregator_builder.py
  federatedscope/core/auxiliaries/trainer_builder.py
  federatedscope/core/auxiliaries/utils.py
  federatedscope/core/auxiliaries/worker_builder.py
  federatedscope/core/configs/cfg_fl_setting.py
  federatedscope/core/configs/cfg_model.py
  federatedscope/core/evaluator.py
  federatedscope/core/fed_runner.py
  federatedscope/core/trainers/tf_trainer.py
  federatedscope/core/trainers/trainer.py
  federatedscope/core/trainers/trainer_nbafl.py
  federatedscope/core/worker/client.py
  federatedscope/core/worker/server.py
  federatedscope/gfl/dataset/splitter/scaffold_splitter.py
  federatedscope/gfl/fedsageplus/worker.py
  federatedscope/gfl/gcflplus/worker.py
  federatedscope/hpo.py
  federatedscope/main.py
  federatedscope/mf/dataset/movielens.py
  federatedscope/mf/trainer/trainer_sgdmf.py
  federatedscope/register.py
  federatedscope/vertical_fl/worker/vertical_server.py
  tests/test_CRA_gan_attack.py
  tests/test_MIA_gradient_ascent.py
  tests/test_PIA_toy.py
  tests/test_ditto.py
  tests/test_efficient_simulation.py
  tests/test_fedem.py
  tests/test_fedopt.py
  tests/test_fedprox.py
  tests/test_fedsageplus.py
  tests/test_femnist.py
  tests/test_graph_node_trainer.py
  tests/test_mf.py
  tests/test_nbafl.py
  tests/test_pfedme.py
  tests/test_rec_IG_opt_attack.py
  tests/test_rec_opt_attack.py
  tests/test_toy_lr.py
  tests/test_vertical_fl.py
Labels: bug, enhancement

#19 Communication efficiency optimization
  README.md
  federatedscope/core/communication.py
  federatedscope/core/gRPC_server.py
  federatedscope/core/message.py
  federatedscope/core/proto/gRPC_comm_manager.proto
  federatedscope/core/proto/gRPC_comm_manager_pb2.py
  federatedscope/core/proto/gRPC_comm_manager_pb2_grpc.py
  federatedscope/example_configs/distributed_client_1.yaml
  federatedscope/example_configs/distributed_client_2.yaml
  federatedscope/example_configs/distributed_server.yaml
  scripts/gen_data.py
Labels: enhancement

#29 Refactored the logger by reducing its redundancy and fixed some minor issues
  federatedscope/attack/example_attack_config/gradient_ascent_MIA_on_femnist.yaml
  federatedscope/attack/worker_as_attacker/server_attacker.py
  federatedscope/config.py
  federatedscope/core/auxiliaries/utils.py
  federatedscope/core/cmd_args.py
  federatedscope/core/configs/cfg_fl_setting.py
  federatedscope/core/fed_runner.py
  federatedscope/core/monitor.py
  federatedscope/core/trainers/trainer.py
  federatedscope/core/worker/base_worker.py
  federatedscope/core/worker/client.py
  federatedscope/core/worker/server.py
  federatedscope/gfl/fedsageplus/worker.py
  federatedscope/gfl/gcflplus/worker.py
  federatedscope/vertical_fl/worker/vertical_server.py
  scripts/personalization_exp_scripts/ditto/ditto_convnet2_on_femnist.yaml
  scripts/personalization_exp_scripts/ditto/ditto_lr_on_synthetic.yaml
  scripts/personalization_exp_scripts/fedbn/fedbn_convnet2_on_femnist.yaml
  scripts/personalization_exp_scripts/fedbn/fedbn_gnn_minibatch_on_multi_task.yaml
  scripts/personalization_exp_scripts/fedem/fedem_convnet2_on_femnist.yaml
  scripts/personalization_exp_scripts/fedem/fedem_lr_on_synthetic.yaml
  scripts/personalization_exp_scripts/pfedme/pfedme_convnet2_on_femnist.yaml
  scripts/personalization_exp_scripts/pfedme/pfedme_lr_on_synthetic.yaml
  tests/test_CRA_gan_attack.py
  tests/test_MIA_gradient_ascent.py
  tests/test_PIA_toy.py
  tests/test_ditto.py
  tests/test_efficient_simulation.py
  tests/test_fedem.py
  tests/test_fedopt.py
  tests/test_fedprox.py
  tests/test_fedsageplus.py
  tests/test_femnist.py
  tests/test_graph_node_trainer.py
  tests/test_mf.py
  tests/test_nbafl.py
  tests/test_pfedme.py
  tests/test_rec_IG_opt_attack.py
  tests/test_rec_opt_attack.py
  tests/test_toy_lr.py
  tests/test_vertical_fl.py
Labels: bug, enhancement

#37 [Feature] FedEx
  LICENSE
  federatedscope/autotune/fedex/__init__.py
  federatedscope/autotune/fedex/client.py
  federatedscope/autotune/fedex/server.py
  federatedscope/core/auxiliaries/worker_builder.py
  federatedscope/core/configs/cfg_hpo.py
  federatedscope/core/configs/cfg_training.py
  federatedscope/core/trainers/context.py
  federatedscope/example_configs/fedex_for_lr.yaml
  federatedscope/example_configs/fedex_search_space.yaml
  tests/test_fedex.py
Labels: Feature

#41 [Hotfix] print the missing ``Final`` results
  federatedscope/core/worker/server.py
Labels: bug

#46 Fix url.
  federatedscope/cv/dataset/leaf_cv.py
  federatedscope/nlp/dataset/leaf_nlp.py
Labels: bug

#43 Added the local training baseline with clients' local early-stoppers
  federatedscope/core/aggregator.py
  federatedscope/core/auxiliaries/aggregator_builder.py
  federatedscope/core/configs/cfg_fl_setting.py
  federatedscope/core/configs/constants.py
  federatedscope/core/constants.py
  federatedscope/core/context.py
  federatedscope/core/monitors/__init__.py
  federatedscope/core/monitors/early_stopper.py
  federatedscope/core/monitors/metric_calculator.py
  federatedscope/core/monitors/monitor.py
  federatedscope/core/trainers/tf_trainer.py
  federatedscope/core/trainers/trainer.py
  federatedscope/core/trainers/trainer_FedEM.py
  federatedscope/core/trainers/trainer_multi_model.py
  federatedscope/core/worker/base_worker.py
  federatedscope/core/worker/client.py
  federatedscope/core/worker/server.py
  federatedscope/vertical_fl/worker/vertical_server.py
  tests/test_local_train_lr.py
Labels: Feature
