Repository alibaba/FederatedScope, pull requests merged in 2022-06, with the labels that each got.

#130 fix early_stop for isolated
  federatedscope/core/worker/server.py
  scripts/contest_exp_scripts/cfg_per_client.yaml
Labels: bug

#124 [Hotfix] Hotfix for issue #122
  federatedscope/core/configs/config.py
  federatedscope/core/trainers/trainer_fedprox.py
  federatedscope/core/trainers/trainer_nbafl.py
Labels: bug

#133 Refactor autotune module
  federatedscope/autotune/__init__.py
  federatedscope/autotune/algos.py
  federatedscope/autotune/choice_types.py
  federatedscope/autotune/fedex/client.py
  federatedscope/autotune/fedex/server.py
  federatedscope/autotune/utils.py
  federatedscope/core/configs/cfg_hpo.py
  federatedscope/core/fed_runner.py
  federatedscope/example_configs/fedex_flat_search_space.yaml
  federatedscope/example_configs/fedex_for_lr.yaml
  federatedscope/example_configs/fedex_grid_search_space.yaml
  federatedscope/example_configs/fedex_search_space.yaml
  federatedscope/example_configs/sha_wrap_fedex.yaml
  federatedscope/example_configs/sha_wrap_fedex_ss.yaml
  federatedscope/example_configs/toy_hpo_ss.yaml
  federatedscope/example_configs/toy_rs.yaml
  federatedscope/example_configs/toy_sha.yaml
  federatedscope/hpo.py
  tests/test_fedex.py
Labels: enhancement

#140 Enable single thread HPO
  federatedscope/autotune/algos.py
  federatedscope/core/configs/cfg_hpo.py
Labels: enhancement

#141 Fix the path to save the policy of FedEx
  federatedscope/autotune/fedex/server.py
Labels: enhancement

#137 [Feature]add wrap fedex
  federatedscope/autotune/algos.py
  federatedscope/autotune/utils.py
  federatedscope/contrib/trainer/example.py
  federatedscope/core/configs/cfg_hpo.py
  federatedscope/example_configs/cora/hpo_ss_fedex.yaml
  federatedscope/example_configs/cora/hpo_ss_fedex_arm.yaml
  federatedscope/example_configs/cora/hpo_ss_fedex_arm_table.yaml
  federatedscope/example_configs/cora/hpo_ss_fedex_grid.yaml
  federatedscope/example_configs/cora/hpo_ss_sha.yaml
  federatedscope/example_configs/cora/run.sh
  federatedscope/example_configs/cora/sha.yaml
  federatedscope/example_configs/cora/sha_wrap_fedex.yaml
  federatedscope/example_configs/cora/sha_wrap_fedex_arm.yaml
  federatedscope/example_configs/femnist/hpo_ss_fedex.yaml
  federatedscope/example_configs/femnist/hpo_ss_fedex_arm.yaml
  federatedscope/example_configs/femnist/hpo_ss_fedex_arm_table.yaml
  federatedscope/example_configs/femnist/hpo_ss_fedex_grid.yaml
  federatedscope/example_configs/femnist/hpo_ss_sha.yaml
  federatedscope/example_configs/femnist/run.sh
  federatedscope/example_configs/femnist/sha.yaml
  federatedscope/example_configs/femnist/sha_wrap_fedex.yaml
  federatedscope/example_configs/femnist/sha_wrap_fedex_arm.yaml
  federatedscope/example_configs/sha_wrap_fedex_arm.yaml
  federatedscope/example_configs/sha_wrap_fedex_ss_table.yaml
Labels: Feature

#145 Improve SHA wrapper
  federatedscope/autotune/algos.py
  federatedscope/autotune/fedex/server.py
  federatedscope/autotune/utils.py
  federatedscope/core/configs/cfg_hpo.py
  federatedscope/example_configs/sha_wrap_fedex_arm.yaml
  federatedscope/example_configs/sha_wrap_fedex_ss_table.yaml
Labels: enhancement

#149 init the pFL-bench scripts
  benchmark/pFL_Bench/FEMNIST-s02/fedavg_convnet2_on_femnist.yaml
  benchmark/pFL_Bench/FEMNIST-s02/run_fedopt_bn_plus_sweep.sh
  benchmark/pFL_Bench/FEMNIST-s02/sweep_ditto.yaml
  benchmark/pFL_Bench/FEMNIST-s02/sweep_fedAvg_FT.yaml
  benchmark/pFL_Bench/FEMNIST-s02/sweep_fedEM_FT_fedBN_fedOpt.yaml
  benchmark/pFL_Bench/README.md
  benchmark/pFL_Bench/res_analysis_plot/get_total_run_time.py
  benchmark/pFL_Bench/res_analysis_plot/plot_paper_figs.py
  benchmark/pFL_Bench/res_analysis_plot/repeat_best_exp.py
  benchmark/pFL_Bench/res_analysis_plot/wandb_to_latex_res.py
  benchmark/pFL_Bench/yaml_best_runs_example/Ditto_FEMNIST-s02.yaml
  benchmark/pFL_Bench/yaml_best_runs_example/FedAvg-FT_FEMNIST-s02.yaml
  benchmark/pFL_Bench/yaml_best_runs_example/FedEM-FedBN-FedOPT-FT_FEMNIST-s02.yaml
Labels: enhancement

#156 fixed typo
  README.md
Labels: documentation

#175 Bugfix for the invalid system metric names, via using worker-specific monitor
  benchmark/FedHPOB/fedhpob/benchmarks/__init__.py
  benchmark/FedHPOB/fedhpob/benchmarks/base_benchmark.py
  benchmark/FedHPOB/fedhpob/benchmarks/surrogate_benchmark.py
  benchmark/FedHPOB/fedhpob/benchmarks/tabular_benchmark.py
  benchmark/FedHPOB/fedhpob/config.py
  benchmark/FedHPOB/fedhpob/optimizers/dehb_optimizer.py
  benchmark/FedHPOB/fedhpob/optimizers/hpbandster_optimizer.py
  benchmark/FedHPOB/fedhpob/optimizers/optuna_optimizer.py
  benchmark/FedHPOB/fedhpob/optimizers/smac_optimizer.py
  benchmark/FedHPOB/fedhpob/utils/cost_model.py
  benchmark/FedHPOB/fedhpob/utils/draw.py
  benchmark/FedHPOB/fedhpob/utils/surrogate_dataloader.py
  benchmark/FedHPOB/fedhpob/utils/tabular_dataloader.py
  benchmark/FedHPOB/fedhpob/utils/util.py
  benchmark/pFL-Bench/res_analysis_plot/get_total_run_time.py
  benchmark/pFL-Bench/res_analysis_plot/render_paper_res.py
  benchmark/pFL-Bench/res_analysis_plot/repeat_best_exp.py
  benchmark/pFL-Bench/res_analysis_plot/wandb_to_latex_res.py
  federatedscope/core/aggregator.py
  federatedscope/core/auxiliaries/aggregator_builder.py
  federatedscope/core/auxiliaries/data_builder.py
  federatedscope/core/auxiliaries/metric_builder.py
  federatedscope/core/auxiliaries/model_builder.py
  federatedscope/core/auxiliaries/trainer_builder.py
  federatedscope/core/auxiliaries/utils.py
  federatedscope/core/configs/cfg_evaluation.py
  federatedscope/core/configs/cfg_fl_algo.py
  federatedscope/core/configs/config.py
  federatedscope/core/monitors/monitor.py
  federatedscope/core/splitters/graph/__init__.py
  federatedscope/core/splitters/graph/scaffold_lda_splitter.py
  federatedscope/core/trainers/context.py
  federatedscope/core/worker/client.py
  federatedscope/core/worker/server.py
  federatedscope/gfl/flitplus/trainer.py
  federatedscope/gfl/loss/vat.py
  federatedscope/gfl/model/mpnn.py
  federatedscope/vertical_fl/worker/vertical_server.py
Labels: bug

#176 Make flop monitoring optional and more user-friendly
  federatedscope/core/configs/cfg_evaluation.py
  federatedscope/core/trainers/torch_trainer.py
  federatedscope/core/trainers/trainer_Ditto.py
  federatedscope/core/trainers/trainer_pFedMe.py
  federatedscope/gfl/trainer/graphtrainer.py
  federatedscope/gfl/trainer/linktrainer.py
  federatedscope/gfl/trainer/nodetrainer.py
  federatedscope/mf/trainer/trainer.py
Labels: enhancement

#154 update splitter for consistent label distribution
  federatedscope/core/auxiliaries/data_builder.py
  federatedscope/core/configs/cfg_data.py
  federatedscope/core/splitters/generic/lda_splitter.py
  federatedscope/core/splitters/utils.py
Labels: enhancement

#196 [HotFix] Fix the url of GFL dataset
  federatedscope/gfl/dataset/recsys.py
Labels: bug

#197 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: skip-changelog
