Repository alibaba/FederatedScope, pull requests merged in 2022-11, with the labels that each got.

#417 Update README.md for installation
  README.md
Labels: documentation

#418 added a fedgraph paper to the paper list
  materials/paper_list/Federated_Graph_Learning/README.md
Labels: documentation

#420 update gfl paper
  materials/paper_list/Federated_Graph_Learning/README.md
Labels: documentation

#421 [pFL papers] added "Keywords" and "Note" columns; fixed some links
  materials/paper_list/Personalized_FL/README.md
Labels: documentation

#413 [Feature] Enhance client_cfg and add new dataset
  federatedscope/autotune/algos.py
  federatedscope/autotune/hpbandster.py
  federatedscope/autotune/smac.py
  federatedscope/autotune/utils.py
  federatedscope/contrib/data/example.py
  federatedscope/contrib/data/mini_graph_dt.py
  federatedscope/core/auxiliaries/logging.py
  federatedscope/core/cmd_args.py
  federatedscope/core/fed_runner.py
  federatedscope/gfl/baseline/mini_graph_dc/fedavg.yaml
  federatedscope/gfl/baseline/mini_graph_dc/fedavg_per_client.yaml
  federatedscope/gfl/trainer/graphtrainer.py
  federatedscope/hpo.py
  federatedscope/main.py
  tests/test_yaml.py
Labels: enhancement

#354 FedGlobalContrast and FedSimCLR baseline
  federatedscope/cl/__init__.py
  federatedscope/cl/baseline/fedcontrastlearning_linearprob_on_cifar10.yaml
  federatedscope/cl/baseline/fedgc_on_cifar10.yaml
  federatedscope/cl/baseline/fedsimclr_on_cifar10.yaml
  federatedscope/cl/baseline/repro_exp/args_cifar10_fedgc.sh
  federatedscope/cl/baseline/repro_exp/args_cifar10_fedsimclr.sh
  federatedscope/cl/baseline/repro_exp/run_contrastive_learning.sh
  federatedscope/cl/baseline/supervised_fedavg_on_cifar10.yaml
  federatedscope/cl/baseline/supervised_local_on_cifar10.yaml
  federatedscope/cl/baseline/unpretrained_linearprob_on_cifar10.yaml
  federatedscope/cl/dataloader/Cifar10.py
  federatedscope/cl/dataloader/__init__.py
  federatedscope/cl/fedgc/client.py
  federatedscope/cl/fedgc/server.py
  federatedscope/cl/fedgc/utils.py
  federatedscope/cl/loss/NT_xentloss.py
  federatedscope/cl/loss/__init__.py
  federatedscope/cl/lr_scheduler/ LR_Scheduler.py
  federatedscope/cl/model/SimCLR.py
  federatedscope/cl/model/__init__.py
  federatedscope/cl/trainer/__init__.py
  federatedscope/cl/trainer/trainer.py
  federatedscope/core/aggregators/aggregator.py
  federatedscope/core/auxiliaries/aggregator_builder.py
  federatedscope/core/auxiliaries/criterion_builder.py
  federatedscope/core/auxiliaries/data_builder.py
  federatedscope/core/auxiliaries/model_builder.py
  federatedscope/core/auxiliaries/trainer_builder.py
  federatedscope/core/auxiliaries/worker_builder.py
  federatedscope/core/configs/constants.py
  federatedscope/core/data/utils.py
  tests/test_simclr_cifar10.py
Labels: Feature

#425 update paper list for FL-Rec
  materials/paper_list/FL-Recommendation/README.md
Labels: documentation

#424 Fix duplicate function names
  federatedscope/core/data/utils.py
Labels: bug

#427 add xgb algo to vertical_fl
  federatedscope/core/auxiliaries/worker_builder.py
  federatedscope/core/configs/cfg_fl_setting.py
  federatedscope/vertical_fl/dataloader/dataloader.py
  federatedscope/vertical_fl/dataset/adult.py
  federatedscope/vertical_fl/xgb_base/__init__.py
  federatedscope/vertical_fl/xgb_base/baseline/xgb_base_on_adult.yaml
  federatedscope/vertical_fl/xgb_base/worker/Feature_sort_base.py
  federatedscope/vertical_fl/xgb_base/worker/Feature_sort_by_bin.py
  federatedscope/vertical_fl/xgb_base/worker/Loss_function.py
  federatedscope/vertical_fl/xgb_base/worker/Test_base.py
  federatedscope/vertical_fl/xgb_base/worker/Tree.py
  federatedscope/vertical_fl/xgb_base/worker/XGBClient.py
  federatedscope/vertical_fl/xgb_base/worker/XGBServer.py
  federatedscope/vertical_fl/xgb_base/worker/__init__.py
  tests/test_xgb.py
Labels: documentation

#436 fix xgb server confict
  federatedscope/vertical_fl/xgb_base/worker/XGBServer.py
Labels: bug

#429 [Feature] krum aggregation rule
  federatedscope/core/aggregators/__init__.py
  federatedscope/core/aggregators/krum_aggregator.py
  federatedscope/core/auxiliaries/aggregator_builder.py
  federatedscope/core/configs/cfg_aggregation.py
  federatedscope/core/workers/client.py
Labels: Feature

#437 Dlg yaml file change
  federatedscope/attack/privacy_attacks/reconstruction_opt.py
  federatedscope/attack/worker_as_attacker/server_attacker.py
  scripts/attack_exp_scripts/privacy_attack/reconstruct_fedavg_opt_on_femnist.yaml
  tests/test_rec_opt_attack.py
Labels: bug

#430 [Feature] Responsiveness sampler
  federatedscope/core/auxiliaries/sampler_builder.py
  federatedscope/core/sampler.py
Labels: enhancement

#388 Add checks for completeness of msg_handler
  .github/workflows/test_distribute.yml
  federatedscope/contrib/worker/example.py
  federatedscope/core/configs/config.py
  federatedscope/core/fed_runner.py
  federatedscope/core/workers/base_client.py
  federatedscope/core/workers/base_server.py
  federatedscope/core/workers/base_worker.py
  federatedscope/core/workers/client.py
  federatedscope/core/workers/server.py
  setup.py
Labels: enhancement

#444 set pin_memory to False to avoid OOM
  federatedscope/core/configs/cfg_data.py
  scripts/README.md
Labels: enhancement

#442 [hotfix] fix update key bug in monitor
  federatedscope/autotune/choice_types.py
  federatedscope/core/monitors/monitor.py
Labels: bug
