Repository alibaba/FederatedScope, pull requests merged in 2022-12, with the labels that each got.

#461 Fix several bugs
  federatedscope/attack/auxiliary/poisoning_data.py
  federatedscope/contrib/data/mini_graph_dt.py
  federatedscope/core/auxiliaries/transform_builder.py
  federatedscope/core/configs/cfg_data.py
  federatedscope/core/configs/cfg_training.py
  federatedscope/core/data/base_translator.py
  federatedscope/core/data/utils.py
  federatedscope/core/splitters/generic/iid_splitter.py
  federatedscope/core/splitters/generic/lda_splitter.py
  federatedscope/cv/baseline/fedavg_convnet2_on_cifar10.yaml
  federatedscope/cv/dataloader/dataloader.py
  federatedscope/cv/dataset/leaf.py
  federatedscope/cv/dataset/leaf_cv.py
  federatedscope/gfl/dataloader/dataloader_graph.py
  federatedscope/gfl/dataloader/dataloader_link.py
  federatedscope/gfl/dataloader/dataloader_node.py
  federatedscope/nlp/dataloader/dataloader.py
Labels: bug

#463 fix b-local dissim
  federatedscope/autotune/fedex/server.py
  federatedscope/core/data/base_translator.py
  federatedscope/core/data/dummy_translator.py
  federatedscope/core/monitors/metric_calculator.py
  federatedscope/core/monitors/monitor.py
  federatedscope/core/workers/server.py
  federatedscope/gfl/fedsageplus/worker.py
Labels: bug

#467 Fix roc_auc
  federatedscope/autotune/utils.py
  federatedscope/core/monitors/metric_calculator.py
Labels: bug

#471 add distributed mode for xgb algo
  federatedscope/vertical_fl/xgb_base/worker/Test_base.py
  federatedscope/vertical_fl/xgb_base/worker/XGBClient.py
  federatedscope/vertical_fl/xgb_base/worker/XGBServer.py
  scripts/distributed_scripts/distributed_configs/distributed_xgb_client_1.yaml
  scripts/distributed_scripts/distributed_configs/distributed_xgb_client_2.yaml
  scripts/distributed_scripts/distributed_configs/distributed_xgb_server.yaml
  scripts/distributed_scripts/run_distributed_xgb.sh
Labels: Tree

#426 Add condition param to autotune; Add feature engineering module
  .github/workflows/test_autotune.yml
  federatedscope/autotune/__init__.py
  federatedscope/autotune/algos.py
  federatedscope/autotune/baseline/fedhpo_vfl.yaml
  federatedscope/autotune/baseline/vfl_ss.yaml
  federatedscope/autotune/hpbandster.py
  federatedscope/autotune/run.py
  federatedscope/autotune/smac.py
  federatedscope/autotune/utils.py
  federatedscope/core/auxiliaries/feat_engr_builder.py
  federatedscope/core/auxiliaries/logging.py
  federatedscope/core/configs/README.md
  federatedscope/core/configs/cfg_data.py
  federatedscope/core/configs/cfg_fl_setting.py
  federatedscope/core/feature/__init__.py
  federatedscope/core/feature/hfl/__init__.py
  federatedscope/core/feature/hfl/preprocess/__init__.py
  federatedscope/core/feature/hfl/preprocess/log_transform.py
  federatedscope/core/feature/hfl/preprocess/min_max_norm.py
  federatedscope/core/feature/hfl/preprocess/quantile_binning.py
  federatedscope/core/feature/hfl/preprocess/standard.py
  federatedscope/core/feature/hfl/preprocess/uniform_binning.py
  federatedscope/core/feature/hfl/selection/__init__.py
  federatedscope/core/feature/hfl/selection/correlation_filter.py
  federatedscope/core/feature/hfl/selection/variance_filter.py
  federatedscope/core/feature/utils.py
  federatedscope/core/feature/vfl/__init__.py
  federatedscope/core/feature/vfl/preprocess/__init__.py
  federatedscope/core/feature/vfl/preprocess/instance_norm.py
  federatedscope/core/feature/vfl/preprocess/log_transform.py
  federatedscope/core/feature/vfl/preprocess/min_max_norm.py
  federatedscope/core/feature/vfl/preprocess/quantile_binning.py
  federatedscope/core/feature/vfl/preprocess/standardization.py
  federatedscope/core/feature/vfl/preprocess/uniform_binning.py
  federatedscope/core/feature/vfl/selection/__init__.py
  federatedscope/core/feature/vfl/selection/correlation_filter.py
  federatedscope/core/feature/vfl/selection/iv_filter.py
  federatedscope/core/feature/vfl/selection/variance_filter.py
  federatedscope/core/fed_runner.py
  federatedscope/core/secure/__init__.py
  federatedscope/core/secure/encrypt/__init__.py
  federatedscope/core/secure/encrypt/dummy_encrypt.py
  federatedscope/core/trainers/trainer_Ditto.py
  federatedscope/core/workers/server.py
  federatedscope/cv/trainer/__init__.py
  federatedscope/hpo.py
  federatedscope/vertical_fl/baseline/vertical_fl.yaml
  federatedscope/vertical_fl/baseline/vertical_on_adult.yaml
  federatedscope/vertical_fl/dataloader/dataloader.py
  federatedscope/vertical_fl/dataset/__init__.py
  federatedscope/vertical_fl/worker/vertical_client.py
  federatedscope/vertical_fl/worker/vertical_server.py
  federatedscope/vertical_fl/xgb_base/baseline/xgb_base_on_abalone.yaml
  federatedscope/vertical_fl/xgb_base/baseline/xgb_base_on_adult.yaml
  federatedscope/vertical_fl/xgb_base/baseline/xgb_base_on_blogfeedback.yaml
  federatedscope/vertical_fl/xgb_base/baseline/xgb_base_on_givemesomecredit.yaml
  federatedscope/vertical_fl/xgb_base/worker/XGBClient.py
  federatedscope/vertical_fl/xgb_base/worker/XGBServer.py
  tests/test_yaml.py
Labels: enhancement, FedHPO-B

#474 Fix name for hpobench
  README.md
  benchmark/FedHPOBench/README.md
  benchmark/FedHPOBench/demo/femnist_surrogate_benchmark.py
  benchmark/FedHPOBench/demo/femnist_tabular_benchmark.py
  benchmark/FedHPOBench/fedhpobench/benchmarks/__init__.py
  benchmark/FedHPOBench/fedhpobench/benchmarks/base_benchmark.py
  benchmark/FedHPOBench/fedhpobench/benchmarks/raw_benchmark.py
  benchmark/FedHPOBench/fedhpobench/benchmarks/surrogate_benchmark.py
  benchmark/FedHPOBench/fedhpobench/benchmarks/tabular_benchmark.py
  benchmark/FedHPOBench/fedhpobench/config.py
  benchmark/FedHPOBench/fedhpobench/optimizers/__init__.py
  benchmark/FedHPOBench/fedhpobench/optimizers/dehb_optimizer.py
  benchmark/FedHPOBench/fedhpobench/optimizers/grid_search.py
  benchmark/FedHPOBench/fedhpobench/optimizers/hpbandster_optimizer.py
  benchmark/FedHPOBench/fedhpobench/optimizers/optuna_optimizer.py
  benchmark/FedHPOBench/fedhpobench/optimizers/smac_optimizer.py
  benchmark/FedHPOBench/fedhpobench/utils/draw.py
  benchmark/FedHPOBench/fedhpobench/utils/monitor.py
  benchmark/FedHPOBench/fedhpobench/utils/runner.py
  benchmark/FedHPOBench/fedhpobench/utils/surrogate_dataloader.py
  benchmark/FedHPOBench/scripts/cross_device/run_hpo_twitter_lr.sh
  benchmark/FedHPOBench/scripts/exp/run_mode.sh
  benchmark/FedHPOBench/scripts/gcn/run_hpo_cora_dp.sh
  benchmark/FedHPOBench/scripts/gcn/run_prox_cora.sh
Labels: bug, FedHPO-B

#475 move "batch_size" from data to dataloader
  federatedscope/vertical_fl/xgb_base/baseline/xgb_base_on_abalone.yaml
  federatedscope/vertical_fl/xgb_base/baseline/xgb_base_on_blogfeedback.yaml
  federatedscope/vertical_fl/xgb_base/baseline/xgb_base_on_givemesomecredit.yaml
  federatedscope/vertical_fl/xgb_base/worker/XGBClient.py
  federatedscope/vertical_fl/xgb_base/worker/XGBServer.py
Labels: bug

#476 fix xgb distribute mode bugs
  federatedscope/autotune/baseline/fedhpo_vfl.yaml
  federatedscope/vertical_fl/xgb_base/baseline/xgb_base_on_abalone.yaml
  federatedscope/vertical_fl/xgb_base/baseline/xgb_base_on_adult.yaml
  federatedscope/vertical_fl/xgb_base/baseline/xgb_base_on_blogfeedback.yaml
  federatedscope/vertical_fl/xgb_base/baseline/xgb_base_on_givemesomecredit.yaml
  federatedscope/vertical_fl/xgb_base/worker/Test_base.py
  federatedscope/vertical_fl/xgb_base/worker/XGBClient.py
  scripts/distributed_scripts/distributed_configs/distributed_xgb_client_1.yaml
  scripts/distributed_scripts/distributed_configs/distributed_xgb_client_2.yaml
  scripts/distributed_scripts/distributed_configs/distributed_xgb_server.yaml
  tests/test_xgb.py
Labels: bug, Feature
