Repository alibaba/FederatedScope, pull requests merged in 2022-05, with the labels that each got.

#52 added some core API reference
  doc/source/core.rst
  federatedscope/core/configs/config.py
  federatedscope/core/configs/constants.py
  federatedscope/core/monitors/monitor.py
Labels: documentation

#55 typos fix
  README.md
Labels: documentation

#57 Update doc/core for api documents
  federatedscope/core/fed_runner.py
  federatedscope/core/worker/base_worker.py
  federatedscope/core/worker/client.py
  federatedscope/core/worker/server.py
Labels: documentation

#60 Add materials (paper lists, tutorials)
  materials/paper_list/FL-NLP/README.md
  materials/paper_list/FL-Recommendation/README.md
  materials/paper_list/Federated Graph Learning/README.md
  materials/paper_list/Personalized_FL/README.md
  materials/tutorial/KDD_2022/README.md
Labels: documentation

#61 Add paper lists
  materials/paper_list/FL-Attacker/README.md
  materials/paper_list/FL-Database/README.md
  materials/paper_list/FL-HPO/README.md
  materials/paper_list/FL-Incentive/README.md
  materials/paper_list/FL-Recommendation/README.md
  materials/paper_list/Federated_Graph_Learning/README.md
Labels: documentation

#67 Add paper list for FedHPO
  materials/paper_list/FL-HPO/README.md
  materials/paper_list/Federated_HPO/README.md
Labels: documentation

#42 Add more models and datasets from external packages.
  enviroment/docker_files/federatedscope-torch1.10-application.Dockerfile
  enviroment/docker_files/federatedscope-torch1.8-application.Dockerfile
  enviroment/requirements-torch1.10-application.txt
  enviroment/requirements-torch1.8-application.txt
  federatedscope/core/auxiliaries/data_builder.py
  federatedscope/core/auxiliaries/model_builder.py
  federatedscope/core/auxiliaries/utils.py
  federatedscope/core/trainers/__init__.py
  federatedscope/core/worker/server.py
  federatedscope/example_configs/openml_lr.yaml
  federatedscope/nlp/baseline/fedavg_bert_on_sst2.yaml
  federatedscope/nlp/baseline/fedavg_transformer_on_imdb.yaml
  federatedscope/nlp/model/__init__.py
  federatedscope/nlp/model/model_builder.py
  federatedscope/nlp/trainer/trainer.py
  tests/test_external_dataset.py
Labels: Feature

#74 [hotfix] Use Specific Versions for transformers
  enviroment/docker_files/federatedscope-torch1.10-application.Dockerfile
  enviroment/docker_files/federatedscope-torch1.8-application.Dockerfile
  enviroment/requirements-torch1.10-application.txt
  enviroment/requirements-torch1.8-application.txt
Labels: bug

#76 [Hotfix] fix url in dblp_new.py
  federatedscope/gfl/dataset/dblp_new.py
Labels: bug

#79 [Feature]Add MLP to model_builder.py
  federatedscope/core/auxiliaries/model_builder.py
  federatedscope/core/configs/cfg_data.py
  federatedscope/core/configs/cfg_model.py
  federatedscope/core/mlp.py
  federatedscope/gfl/model/__init__.py
  federatedscope/gfl/model/gin.py
  federatedscope/gfl/model/link_level.py
  federatedscope/gfl/model/model_builder.py
  scripts/gnn_exp_scripts/run_link_level_opt.sh
  scripts/gnn_exp_scripts/run_link_level_prox.sh
  scripts/gnn_exp_scripts/run_node_level_opt.sh
  scripts/gnn_exp_scripts/run_node_level_prox.sh
Labels: Feature

#83 Add readme for vfl
  federatedscope/core/monitors/monitor.py
  federatedscope/vertical_fl/README.md
  federatedscope/vertical_fl/vertical_fl.yaml
Labels: documentation

#85 An example for distributed mode
  README.md
Labels: documentation

#88 Demo how to use SMAC for FedHPO
  demo/smac/gp.py
  demo/smac/rf.py
Labels: documentation

#95 [HotFIx] Fix download url for windows and typos in README.md
  README.md
  federatedscope/core/auxiliaries/utils.py
  federatedscope/cv/dataset/leaf_cv.py
  federatedscope/gfl/dataset/dblp_new.py
  federatedscope/gfl/dataset/recsys.py
  federatedscope/nlp/dataset/leaf_nlp.py
Labels: bug

#97 update readme
  README.md
  federatedscope/core/configs/cfg_asyn.py
Labels: documentation

#101 fix dataset download urls
  federatedscope/cv/dataset/leaf_cv.py
  federatedscope/gfl/dataset/dblp_new.py
  federatedscope/gfl/dataset/recsys.py
  federatedscope/nlp/dataset/leaf_nlp.py
Labels: bug

#87 [feature] FLIT for federated graph classification/regression
  .gitignore
  federatedscope/core/auxiliaries/data_builder.py
  federatedscope/core/auxiliaries/model_builder.py
  federatedscope/core/auxiliaries/splitter_builder.py
  federatedscope/core/auxiliaries/trainer_builder.py
  federatedscope/core/configs/cfg_fl_algo.py
  federatedscope/core/splitters/graph/__init__.py
  federatedscope/core/splitters/graph/scaffold_lda_splitter.py
  federatedscope/gfl/flitplus/__init__.py
  federatedscope/gfl/flitplus/fedalgo_cls.yaml
  federatedscope/gfl/flitplus/trainer.py
  federatedscope/gfl/loss/vat.py
  federatedscope/gfl/model/model_builder.py
  federatedscope/gfl/model/mpnn.py
  scripts/flit_exp_scripts/fedalgo.sh
  scripts/flit_exp_scripts/run_fedavg-fedfocal-flit_cls.sh
  scripts/flit_exp_scripts/run_fedprox_cls.sh
  scripts/flit_exp_scripts/run_fedvat_cls.sh
  scripts/flit_exp_scripts/run_flitplus_cls.sh
Labels: Feature

#90 Enhanced monitor with system metrics logging and wandb support
  enviroment/docker_files/federatedscope-torch1.10-application.Dockerfile
  enviroment/docker_files/federatedscope-torch1.10.Dockerfile
  enviroment/docker_files/federatedscope-torch1.8-application.Dockerfile
  enviroment/requirements-torch1.10-application.txt
  enviroment/requirements-torch1.10.txt
  enviroment/requirements-torch1.8-application.txt
  federatedscope/core/auxiliaries/trainer_builder.py
  federatedscope/core/auxiliaries/utils.py
  federatedscope/core/communication.py
  federatedscope/core/configs/__init__.py
  federatedscope/core/configs/cfg_data.py
  federatedscope/core/configs/config.py
  federatedscope/core/fed_runner.py
  federatedscope/core/message.py
  federatedscope/core/monitors/monitor.py
  federatedscope/core/trainers/trainer.py
  federatedscope/core/trainers/trainer_Ditto.py
  federatedscope/core/trainers/trainer_FedEM.py
  federatedscope/core/trainers/trainer_pFedMe.py
  federatedscope/core/worker/base_worker.py
  federatedscope/core/worker/client.py
  federatedscope/core/worker/server.py
  federatedscope/gfl/fedsageplus/trainer.py
  federatedscope/gfl/fedsageplus/worker.py
  federatedscope/gfl/trainer/graphtrainer.py
  federatedscope/gfl/trainer/linktrainer.py
  federatedscope/gfl/trainer/nodetrainer.py
  federatedscope/mf/trainer/trainer.py
  scripts/parse_exp_results_wandb.py
  setup.py
Labels: enhancement, Feature

#103 [HotFix] Fix eval bug.
  federatedscope/core/worker/server.py
Labels: bug

#109 [HotFix]Fix logger
  federatedscope/core/monitors/monitor.py
Labels: bug

#111 A quadratic objective function-based experiment
  demo/synthetic.py
  federatedscope/core/auxiliaries/data_builder.py
  federatedscope/core/auxiliaries/model_builder.py
  federatedscope/core/cmd_args.py
  federatedscope/core/configs/cfg_data.py
  federatedscope/core/fed_runner.py
  federatedscope/main.py
  federatedscope/tabular/__init__.py
  federatedscope/tabular/dataloader/__init__.py
  federatedscope/tabular/dataloader/quadratic.py
  federatedscope/tabular/model/__init__.py
  federatedscope/tabular/model/quadratic.py
Labels: Feature

#115 Bug fix for issue #113
  federatedscope/core/fed_runner.py
Labels: bug

#119 [HotFix] Fix contrib.
  federatedscope/core/auxiliaries/data_builder.py
  federatedscope/core/auxiliaries/metric_builder.py
  federatedscope/core/auxiliaries/model_builder.py
  federatedscope/core/auxiliaries/trainer_builder.py
Labels: bug

#120 Calibrate FedEx
  federatedscope/attack/auxiliary/attack_trainer_builder.py
  federatedscope/attack/trainer/GAN_trainer.py
  federatedscope/attack/trainer/MIA_invert_gradient_trainer.py
  federatedscope/attack/trainer/PIA_trainer.py
  federatedscope/autotune/fedex/client.py
  federatedscope/autotune/fedex/server.py
  federatedscope/core/auxiliaries/trainer_builder.py
  federatedscope/core/configs/cfg_fl_setting.py
  federatedscope/core/configs/cfg_hpo.py
  federatedscope/core/configs/config.py
  federatedscope/core/trainers/__init__.py
  federatedscope/core/trainers/torch_trainer.py
  federatedscope/core/trainers/trainer.py
  federatedscope/core/trainers/trainer_Ditto.py
  federatedscope/core/trainers/trainer_FedEM.py
  federatedscope/core/trainers/trainer_fedprox.py
  federatedscope/core/trainers/trainer_multi_model.py
  federatedscope/core/trainers/trainer_nbafl.py
  federatedscope/core/trainers/trainer_pFedMe.py
  federatedscope/cv/trainer/trainer.py
  federatedscope/example_configs/fedex_for_lr.yaml
  federatedscope/example_configs/quadratic.yaml
  federatedscope/example_configs/quadratic_clientwise.yaml
  federatedscope/gfl/trainer/graphtrainer.py
  federatedscope/gfl/trainer/linktrainer.py
  federatedscope/gfl/trainer/nodetrainer.py
  federatedscope/mf/trainer/trainer.py
  federatedscope/nlp/trainer/trainer.py
Labels: enhancement
