Repository alibaba/FederatedScope, pull requests merged in 2022-07, with the labels that each got.

#192 [Doc] Fix the guidance of installation and setup
  .pre-commit-config.yaml
  README.md
  enviroment/extra_dependencies_torch1.10-application.sh
  federatedscope/__init__.py
  meta.yaml
  setup.py
Labels: documentation, enhancement

#201 Feature/incentive paper
  README.md
  materials/paper_list/FL-Incentive/README.md
Labels: documentation

#202 add backdoor paper list
  README.md
  materials/paper_list/FL-Attacker/README.md
Labels: documentation

#204 Support more datasets for distribute mode
  federatedscope/core/auxiliaries/data_builder.py
  federatedscope/core/configs/cfg_fl_setting.py
Labels: enhancement

#207 [HotFix] Format code
  .pre-commit-config.yaml
  .style.yapf
  benchmark/B-FHTL/scripts/Graph-DC/fedbn_ft.yaml
  doc/source/conf.py
  enviroment/docker_files/federatedscope-jupyterhub/jupyter_server_config.py
  federatedscope/contrib/metrics/example.py
  federatedscope/contrib/model/example.py
  federatedscope/core/configs/cfg_data.py
  federatedscope/core/splitters/generic/lda_splitter.py
  federatedscope/core/splitters/utils.py
  federatedscope/core/trainers/trainer.py
  federatedscope/cv/dataset/leaf.py
  federatedscope/cv/model/cnn.py
  federatedscope/cv/model/model_builder.py
  federatedscope/example_configs/hpo_for_gnn.yaml
  federatedscope/gfl/dataset/kg.py
  federatedscope/gfl/dataset/utils.py
  federatedscope/gfl/fedsageplus/utils.py
  federatedscope/gfl/model/fedsageplus.py
  federatedscope/gfl/model/gat.py
  federatedscope/gfl/model/gcn.py
  federatedscope/gfl/model/sage.py
  federatedscope/nlp/dataloader/dataloader.py
  federatedscope/nlp/dataset/leaf_synthetic.py
  federatedscope/nlp/loss/character_loss.py
  federatedscope/parse_exp_results.py
  regression.sh
  scripts/gen_data.py
  scripts/parse_exp_results_wandb.py
  tests/run.py
Labels: bug

#200 [feature] samplers
  federatedscope/attack/worker_as_attacker/server_attacker.py
  federatedscope/core/auxiliaries/sampler_builder.py
  federatedscope/core/configs/cfg_fl_setting.py
  federatedscope/core/sampler.py
  federatedscope/core/worker/server.py
Labels: Feature

#205 Changes for format checking
  .pre-commit-config.yaml
  README.md
  setup.py
Labels: skip-changelog

#210 bugfix for invalid sample_client_num
  federatedscope/core/configs/cfg_fl_setting.py
  tests/test_femnist.py
Labels: bug

#212 fix the cpu and memory wastage problems caused by multiprocess
  federatedscope/core/auxiliaries/utils.py
  federatedscope/core/fed_runner.py
Labels: bug

#213 [HotFix] workaround for type convertion
  federatedscope/core/aggregator.py
  federatedscope/core/trainers/torch_trainer.py
  federatedscope/cv/model/cnn.py
Labels: skip-changelog

#206 support logging client-wise training info via wandb
  federatedscope/core/configs/cfg_data.py
  federatedscope/core/configs/cfg_evaluation.py
  federatedscope/core/monitors/monitor.py
  federatedscope/core/trainers/trainer.py
  federatedscope/core/worker/client.py
Labels: enhancement

#194 [Feature] Add Release Drafter
  .github/release-drafter.yml
Labels: skip-changelog

#216 reformat existing code
  federatedscope/core/configs/cfg_data.py
  federatedscope/core/trainers/trainer.py
Labels: skip-changelog

#223 [HotFix] Fix invalid logging in distributed mode
  federatedscope/core/auxiliaries/eunms.py
  federatedscope/core/auxiliaries/utils.py
  federatedscope/core/configs/cfg_hpo.py
  federatedscope/core/configs/cfg_training.py
  federatedscope/core/trainers/context.py
  federatedscope/core/trainers/torch_trainer.py
  federatedscope/core/trainers/trainer_Ditto.py
  federatedscope/core/worker/client.py
Labels: bug

#220 support both pre- and post-merging data for the "global" baseline
  federatedscope/core/auxiliaries/data_builder.py
  federatedscope/core/auxiliaries/utils.py
  federatedscope/core/configs/cfg_data.py
  federatedscope/core/configs/cfg_fl_setting.py
  federatedscope/core/fed_runner.py
  federatedscope/core/worker/client.py
  federatedscope/example_configs/femnist_global_train.yaml
Labels: enhancement

#226 enabled precision configuartion when printing out float numbers
  federatedscope/core/auxiliaries/utils.py
  federatedscope/core/configs/config.py
  tests/test_CRA_gan_attack.py
  tests/test_MIA_gradient_ascent.py
  tests/test_PIA_toy.py
  tests/test_ditto.py
  tests/test_external_dataset.py
  tests/test_fedem.py
  tests/test_fedopt.py
  tests/test_fedprox.py
  tests/test_fedsageplus.py
  tests/test_femnist.py
  tests/test_finetune_lr.py
  tests/test_global_train_lr.py
  tests/test_graph_node_trainer.py
  tests/test_local_train_lr.py
  tests/test_mf.py
  tests/test_nbafl.py
  tests/test_optimizer.py
  tests/test_pfedme.py
  tests/test_rec_IG_opt_attack.py
  tests/test_rec_opt_attack.py
  tests/test_toy_lr.py
  tests/test_vertical_fl.py
Labels: enhancement

#100 [Feature] Enabled un-seen clients case to check the participation generalization gap
  federatedscope/autotune/fedex/server.py
  federatedscope/core/configs/cfg_fl_setting.py
  federatedscope/core/fed_runner.py
  federatedscope/core/sampler.py
  federatedscope/core/worker/client.py
  federatedscope/core/worker/server.py
  tests/test_unseen_clients_lr.py
Labels: enhancement, Feature

#228 Enable to use share_local_model in non-online aggregation
  federatedscope/autotune/fedex/client.py
  federatedscope/core/trainers/tf_trainer.py
  federatedscope/core/trainers/torch_trainer.py
  federatedscope/core/trainers/trainer.py
  federatedscope/core/trainers/trainer_multi_model.py
  federatedscope/core/worker/client.py
  federatedscope/gfl/fedsageplus/worker.py
  federatedscope/gfl/gcflplus/worker.py
Labels: enhancement

#232 [Bugfix]Fix type conversion error in distributed mode
  federatedscope/core/aggregator.py
  federatedscope/core/auxiliaries/utils.py
  federatedscope/core/trainers/torch_trainer.py
  federatedscope/example_configs/distributed_femnist_client1.yaml
  federatedscope/example_configs/distributed_femnist_client2.yaml
  federatedscope/example_configs/distributed_femnist_client3.yaml
  federatedscope/example_configs/distributed_femnist_server.yaml
Labels: bug

#231 [Feature&Bugfix] Add notebook & Add yaml unitest
  federatedscope/attack/example_attack_config/CRA_fedavg_convnet2_on_femnist.yaml
  federatedscope/attack/example_attack_config/CRA_fedavg_convnet2_on_femnist_gpu.yaml
  federatedscope/attack/example_attack_config/PIA_toy.yaml
  federatedscope/attack/example_attack_config/gradient_ascent_MIA_on_femnist.yaml
  federatedscope/attack/example_attack_config/reconstruct_IG_fedavg_opt_on_femnist.yaml
  federatedscope/attack/example_attack_config/reconstruct_fedavg_opt_on_femnist.yaml
  federatedscope/gfl/baseline/fedavg_gcn_fullbatch_on_dblpnew.yaml
  federatedscope/gfl/baseline/fedavg_gcn_minibatch_on_hiv.yaml
  federatedscope/gfl/baseline/fedavg_gcn_minibatch_on_kg.yaml
  federatedscope/gfl/baseline/fedavg_gnn_minibatch_on_multi_task.yaml
  federatedscope/gfl/baseline/fedavg_gnn_minibatch_on_multi_task_total_samples_aggr.yaml
  federatedscope/gfl/baseline/fedavg_gnn_node_fullbatch_citation.yaml
  federatedscope/gfl/baseline/fedavg_on_cSBM.yaml
  federatedscope/gfl/baseline/fedavg_sage_minibatch_on_dblpnew.yaml
  federatedscope/gfl/baseline/fedavg_wpsn_on_cSBM.yaml
  federatedscope/gfl/baseline/fedbn_gnn_minibatch_on_multi_task.yaml
  federatedscope/gfl/baseline/local_gnn_node_fullbatch_citation.yaml
  federatedscope/gfl/gcflplus/gcflplus_on_multi_task.yaml
  federatedscope/mf/baseline/hfl-sgdmf_fedavg_standalone_on_movielens1m.yaml
  federatedscope/mf/baseline/hfl_fedavg_standalone_on_movielens1m.yaml
  federatedscope/mf/baseline/vfl-sgdmf_fedavg_standalone_on_movielens1m.yaml
  federatedscope/mf/baseline/vfl_fedavg_standalone_on_movielens1m.yaml
  federatedscope/nlp/baseline/fedavg_lr_on_synthetic.yaml
  federatedscope/nlp/baseline/fedavg_lr_on_twitter.yaml
  federatedscope/nlp/baseline/fedavg_lstm_on_subreddit.yaml
  federatedscope/vertical_fl/vertical_fl.yaml
  materials/notebook/01_quick_start.ipynb
  materials/notebook/02_start_your_own_case.ipynb
  materials/notebook/03_personalized_FL.ipynb
  materials/notebook/Welcome.ipynb
  scripts/ci_test.sh
  scripts/format.sh
  tests/test_yaml.py
Labels: bug, Feature

#237 fix the wrongly early_stopper.track_and_check calling in client
  federatedscope/core/monitors/early_stopper.py
  federatedscope/core/worker/client.py
Labels: bug

#234 clarify the term "individual" used in logging
  federatedscope/core/auxiliaries/utils.py
  federatedscope/core/monitors/monitor.py
  federatedscope/core/worker/server.py
  tests/test_mf.py
Labels: enhancement

#227 Some modification for CIKMCUP
  federatedscope/core/auxiliaries/data_builder.py
  federatedscope/core/configs/cfg_evaluation.py
  federatedscope/core/monitors/metric_calculator.py
  federatedscope/core/monitors/monitor.py
  federatedscope/gfl/baseline/fedavg_gin_minibatch_on_cikmcup.yaml
  federatedscope/gfl/baseline/fedavg_gin_minibatch_on_cikmcup_per_client.yaml
  federatedscope/gfl/baseline/isolated_gin_minibatch_on_cikmcup.yaml
  federatedscope/gfl/baseline/isolated_gin_minibatch_on_cikmcup_per_client.yaml
  federatedscope/gfl/dataset/__init__.py
  federatedscope/gfl/dataset/cikm_cup.py
  federatedscope/gfl/model/model_builder.py
  federatedscope/gfl/trainer/graphtrainer.py
  tests/test_yaml.py
Labels: Feature

#225 [Feature] asynchronous training strategies
  LICENSE
  README.md
  federatedscope/attack/worker_as_attacker/server_attacker.py
  federatedscope/autotune/fedex/server.py
  federatedscope/core/aggregator.py
  federatedscope/core/auxiliaries/aggregator_builder.py
  federatedscope/core/auxiliaries/data_builder.py
  federatedscope/core/auxiliaries/utils.py
  federatedscope/core/configs/cfg_asyn.py
  federatedscope/core/configs/cfg_fl_setting.py
  federatedscope/core/fed_runner.py
  federatedscope/core/message.py
  federatedscope/core/worker/client.py
  federatedscope/core/worker/server.py
  federatedscope/cv/model/model_builder.py
  federatedscope/example_configs/asyn_cifar10.yaml
  federatedscope/gfl/fedsageplus/worker.py
  federatedscope/gfl/gcflplus/worker.py
  federatedscope/vertical_fl/dataloader/dataloader.py
  tests/test_asyn_cifar10.py
Labels: Feature

#242 Fix typos in README.md within the cikm22competition branch
  README.md
  environment/docker_files/README.md
  environment/docker_files/federatedscope-jupyterhub/Dockerfile
  environment/docker_files/federatedscope-jupyterhub/fix-permissions
  environment/docker_files/federatedscope-jupyterhub/jupyter_server_config.py
  environment/docker_files/federatedscope-jupyterhub/start-notebook.sh
  environment/docker_files/federatedscope-jupyterhub/start-singleuser.sh
  environment/docker_files/federatedscope-jupyterhub/start.sh
  environment/docker_files/federatedscope-torch1.10-application.Dockerfile
  environment/docker_files/federatedscope-torch1.10.Dockerfile
  environment/docker_files/federatedscope-torch1.8-application.Dockerfile
  environment/extra_dependencies_torch1.10-application.sh
  environment/requirements-torch1.10-application.txt
  environment/requirements-torch1.10.txt
  environment/requirements-torch1.8-application.txt
Labels: documentation

#244 Update README.md in master
  README.md
Labels: skip-changelog

#256 Change save directory into `outdir`
  federatedscope/core/configs/cfg_evaluation.py
  federatedscope/core/fed_runner.py
  federatedscope/core/worker/client.py
  federatedscope/gfl/dataset/cikm_cup.py
Labels: enhancement

#239 Support different types of key when communicating via grpc
  federatedscope/core/communication.py
  federatedscope/core/message.py
  federatedscope/core/proto/gRPC_comm_manager.proto
  federatedscope/core/proto/gRPC_comm_manager_pb2.py
  federatedscope/core/proto/gRPC_comm_manager_pb2_grpc.py
  federatedscope/core/worker/server.py
  federatedscope/vertical_fl/dataloader/dataloader.py
Labels: enhancement

#260 support monitoring the client-wise wandb info
  federatedscope/core/auxiliaries/utils.py
Labels: enhancement

#257 [Feature] Add organizer to FS
  federatedscope/core/cmd_args.py
  federatedscope/core/configs/cfg_evaluation.py
  federatedscope/core/configs/config.py
  federatedscope/core/monitors/metric_calculator.py
  federatedscope/core/monitors/monitor.py
  federatedscope/example_configs/distributed_femnist_client1.yaml
  federatedscope/example_configs/distributed_femnist_client2.yaml
  federatedscope/example_configs/distributed_femnist_client3.yaml
  federatedscope/example_configs/distributed_femnist_server.yaml
  federatedscope/gfl/dataset/__init__.py
  federatedscope/gfl/dataset/cikm_cup.py
  federatedscope/main.py
  federatedscope/organizer/README.md
  federatedscope/organizer/__init__.py
  federatedscope/organizer/cfg_client.py
  federatedscope/organizer/cfg_server.py
  federatedscope/organizer/client.py
  federatedscope/organizer/server.py
  federatedscope/organizer/utils.py
  setup.py
  tests/test_yaml.py
Labels: Feature

#261 [Hotfix] Fix saving directory for torchtext
  tests/test_external_dataset.py
Labels: skip-changelog

#248 [Feature] Add learning rate scheduler in FS
  federatedscope/core/auxiliaries/scheduler_builder.py
  federatedscope/core/configs/cfg_training.py
  federatedscope/core/trainers/torch_trainer.py
Labels: Feature

#263 [Hotfix]Accelerated data loading
  federatedscope/gfl/dataset/cikm_cup.py
Labels: enhancement

#266 [Hotfix] Skip cfg check when not use
  federatedscope/core/configs/cfg_asyn.py
  federatedscope/core/trainers/torch_trainer.py
Labels: bug

#269 [Workaround] Fix personalization when module has lazy load hooks
  federatedscope/attack/privacy_attacks/passive_PIA.py
  federatedscope/autotune/fedex/server.py
  federatedscope/core/auxiliaries/utils.py
  federatedscope/core/trainers/torch_trainer.py
  federatedscope/core/worker/server.py
Labels: bug

#259 [Feature] Add Lifecycle management for the variables in Context
  federatedscope/attack/auxiliary/create_edgeset.py
  federatedscope/attack/auxiliary/poisoning_data.py
  federatedscope/attack/trainer/MIA_invert_gradient_trainer.py
  federatedscope/attack/trainer/benign_trainer.py
  federatedscope/contrib/metrics/example.py
  federatedscope/contrib/metrics/poison_acc.py
  federatedscope/core/auxiliaries/enums.py
  federatedscope/core/auxiliaries/utils.py
  federatedscope/core/monitors/metric_calculator.py
  federatedscope/core/trainers/context.py
  federatedscope/core/trainers/tf_trainer.py
  federatedscope/core/trainers/torch_trainer.py
  federatedscope/core/trainers/trainer.py
  federatedscope/core/trainers/trainer_Ditto.py
  federatedscope/core/trainers/trainer_FedEM.py
  federatedscope/core/trainers/trainer_multi_model.py
  federatedscope/gfl/flitplus/trainer.py
  federatedscope/gfl/trainer/graphtrainer.py
  federatedscope/gfl/trainer/linktrainer.py
  federatedscope/gfl/trainer/nodetrainer.py
  federatedscope/mf/trainer/trainer.py
  tests/test_backdoor_attack.py
Labels: Feature

#271 bugfix for the ditto trainer
  federatedscope/core/trainers/trainer_Ditto.py
  tests/test_ditto.py
Labels: bug

#272 add news for releasing v0.2.0
  README.md
Labels: documentation

#276 modify version
  README.md
  federatedscope/__init__.py
  federatedscope/organizer/cfg_client.py
  meta.yaml
  setup.py
Labels: documentation
