Repository alibaba/FederatedScope, pull requests merged in 2022-08, with the labels that each got.

#277 Supplement more comments for datasets and splitters
  LICENSE
  federatedscope/gfl/dataset/recsys.py
Labels: skip-changelog

#282 update readme for distribute mode
  README.md
Labels: documentation

#281 [Feature] Add cross-device recsys dataset Netflix
  federatedscope/core/auxiliaries/data_builder.py
  federatedscope/mf/baseline/hfl_fedavg_standalone_on_netflix.yaml
  federatedscope/mf/dataloader/dataloader.py
  federatedscope/mf/dataset/movielens.py
  federatedscope/mf/dataset/netflix.py
  federatedscope/mf/model/model.py
Labels: Feature

#283 update paper_list/FL-NLP
  materials/paper_list/FL-NLP/README.md
Labels: documentation

#285 Add README.md for configs (an example)
  federatedscope/core/configs/README.md
Labels: documentation

#288 Fix path in document and script
  benchmark/FedHPOB/scripts/lr/run_hpo_twitter_lr.sh
  federatedscope/gfl/README.md
Labels: skip-changelog

#286 Fix README in FedHPOB
  .flake8
  benchmark/FedHPOB/README.md
  benchmark/FedHPOB/fedhpob/__init__.py
  benchmark/FedHPOB/fedhpob/benchmarks/raw_benchmark.py
  benchmark/FedHPOB/fedhpob/benchmarks/surrogate_benchmark.py
  benchmark/FedHPOB/fedhpob/benchmarks/tabular_benchmark.py
  benchmark/FedHPOB/fedhpob/optimizers/__init__.py
  benchmark/FedHPOB/fedhpob/optimizers/hpbandster_optimizer.py
  benchmark/FedHPOB/fedhpob/optimizers/optuna_optimizer.py
  benchmark/FedHPOB/fedhpob/optimizers/smac_optimizer.py
  benchmark/FedHPOB/fedhpob/utils/draw.py
  benchmark/FedHPOB/fedhpob/utils/monitor.py
  benchmark/FedHPOB/fedhpob/utils/surrogate_dataloader.py
  benchmark/FedHPOB/fedhpob/utils/util.py
  benchmark/FedHPOB/scripts/format.sh
  benchmark/FedHPOB/scripts/gcn/pubmed.yaml
Labels: documentation, FedHPO-B

#287 readme for cfg_asyn
  federatedscope/core/configs/README.md
Labels: documentation

#291 Fix client state error
  federatedscope/autotune/fedex/server.py
Labels: bug

#292 Add training and DP related configuration in README.md
  federatedscope/core/configs/README.md
Labels: documentation

#293 readme for cfg_fl_setting
  federatedscope/core/configs/README.md
Labels: documentation

#296 readme for cfg.data
  federatedscope/core/configs/README.md
Labels: documentation

#297 updated hpo args
  federatedscope/core/configs/README.md
  federatedscope/core/configs/cfg_hpo.py
Labels: documentation

#300 readme for cfg_model
  federatedscope/core/configs/README.md
Labels: documentation

#301 update cfg docs w.r.t. evaluation and fl algos.
  federatedscope/core/configs/README.md
  federatedscope/core/configs/cfg_data.py
  federatedscope/core/configs/cfg_evaluation.py
  federatedscope/core/configs/cfg_fl_algo.py
Labels: documentation

#295 Add code structure in readme
  README.md
  federatedscope/attack/worker_as_attacker/server_attacker.py
  federatedscope/autotune/fedex/client.py
  federatedscope/autotune/fedex/server.py
  federatedscope/core/auxiliaries/worker_builder.py
  federatedscope/core/fed_runner.py
  federatedscope/core/workers/__init__.py
  federatedscope/core/workers/base_worker.py
  federatedscope/core/workers/client.py
  federatedscope/core/workers/server.py
  federatedscope/gfl/fedsageplus/worker.py
  federatedscope/gfl/gcflplus/worker.py
  federatedscope/vertical_fl/worker/vertical_client.py
  federatedscope/vertical_fl/worker/vertical_server.py
Labels: documentation

#303 Update cfg docs
  benchmark/pFL-Bench/yaml_best_runs_example/Ditto_FEMNIST-s02.yaml
  benchmark/pFL-Bench/yaml_best_runs_example/FedAvg-FT_FEMNIST-s02.yaml
  benchmark/pFL-Bench/yaml_best_runs_example/FedEM-FedBN-FedOPT-FT_FEMNIST-s02.yaml
  federatedscope/core/auxiliaries/data_builder.py
  federatedscope/core/configs/README.md
Labels: documentation

#306 [Hotfix]fix github url in gfl
  federatedscope/gfl/dataset/kg.py
  federatedscope/gfl/dataset/recsys.py
Labels: bug

#307 apply the updates according to the exp of fedhpo-b
  federatedscope/example_configs/femnist/avg/rs.yaml
  federatedscope/example_configs/femnist/avg/rs_wrap.yaml
  federatedscope/example_configs/femnist/avg/sha.yaml
  federatedscope/example_configs/femnist/avg/sha_wrap.yaml
  federatedscope/example_configs/femnist/avg/ss.yaml
Labels: FedHPO-B

#312 fix out_dir in wrap_fedex
  federatedscope/example_configs/femnist/avg/bo_gp.yaml
  federatedscope/example_configs/femnist/avg/bo_gp_wrap.yaml
  federatedscope/example_configs/femnist/avg/bo_kde.yaml
  federatedscope/example_configs/femnist/avg/bo_kde_wrap.yaml
  federatedscope/example_configs/femnist/avg/bo_rf.yaml
  federatedscope/example_configs/femnist/avg/bo_rf_wrap.yaml
  federatedscope/example_configs/femnist/avg/bohb.yaml
  federatedscope/example_configs/femnist/avg/bohb_wrap.yaml
Labels: skip-changelog

#314 [Hotfix] Make the message comparator more robust
  federatedscope/core/message.py
Labels: bug

#315 [BugFix] Fix README and Tabular api
  benchmark/FedHPOB/README.md
  benchmark/FedHPOB/fedhpob/benchmarks/tabular_benchmark.py
Labels: bug, FedHPO-B

#316 add atk doc to script
  federatedscope/attack/example_attack_config/CRA_fedavg_convnet2_on_femnist.yaml
  scripts/README.md
  scripts/attack_exp_scripts/backdoor_attack/backdoor_badnet_fedavg_convnet2_on_femnist.yaml
  scripts/attack_exp_scripts/privacy_attack/CRA_fedavg_convnet2_on_femnist.yaml
  scripts/attack_exp_scripts/privacy_attack/PIA_toy.yaml
  scripts/attack_exp_scripts/privacy_attack/gradient_ascent_MIA_on_femnist.yaml
  scripts/attack_exp_scripts/privacy_attack/reconstruct_IG_fedavg_opt_on_femnist.yaml
  scripts/attack_exp_scripts/privacy_attack/reconstruct_fedavg_opt_on_femnist.yaml
Labels: documentation

#318 [hotfix] cmd parser
  federatedscope/core/cmd_args.py
Labels: bug

#320 [Feature] Add twitter to FedHPOB
  benchmark/FedHPOB/README.md
  benchmark/FedHPOB/fedhpob/benchmarks/base_benchmark.py
  benchmark/FedHPOB/fedhpob/config.py
  benchmark/FedHPOB/scripts/cross_device/run_hpo_twitter_lr.sh
  benchmark/FedHPOB/scripts/cross_device/twitter.yaml
Labels: FedHPO-B

#319 bugfix for scripts
  README.md
  federatedscope/core/workers/server.py
  scripts/README.md
  scripts/attack_exp_scripts/privacy_attack/PIA_toy.yaml
  scripts/distributed_scripts/run_distributed_lr.sh
  scripts/example_configs/asyn_cifar10.yaml
Labels: documentation

#322 [Notebook] Update notebook tutorials
  README.md
  materials/notebook/(CN)CIKMCUP2022.ipynb
  materials/notebook/(EN)CIKMCUP2022.ipynb
  materials/notebook/01_quick_start.ipynb
  materials/notebook/02_start_your_own_case.ipynb
  materials/notebook/03_personalized_FL.ipynb
  materials/notebook/Welcome.ipynb
Labels: documentation

#323 [hotfix] cfg node
  federatedscope/core/configs/yacs_config.py
Labels: bug

#326 update readme
  README.md
Labels: documentation

#329 [bugfix] Remove notebook output logs
  materials/notebook/02_start_your_own_case.ipynb
Labels: skip-changelog

#328 Feature/doc scripts pfl
  scripts/README.md
Labels: documentation

#333 supplement copyright of GraphGym
  LICENSE
Labels: documentation

#331 [Scripts] Add scripts for FedProx on Cora
  benchmark/FedHPOB/scripts/gcn/cora_prox.yaml
  benchmark/FedHPOB/scripts/gcn/run_prox_cora.sh
  environment/extra_dependencies_torch1.10-application.sh
Labels: FedHPO-B

#338 [Feature] Add utils for draw landscape
  benchmark/FedHPOB/fedhpob/utils/draw.py
Labels: Feature, FedHPO-B

#317 [bugfix] Fix one-shot exp utils
  benchmark/FedHPOB/README.md
  benchmark/FedHPOB/fedhpob/benchmarks/surrogate_benchmark.py
  federatedscope/autotune/hpbandster.py
  federatedscope/autotune/smac.py
  federatedscope/autotune/utils.py
  scripts/example_configs/femnist/avg/bo_gp_wrap.yaml
  scripts/example_configs/femnist/avg/bo_kde_wrap.yaml
  scripts/example_configs/femnist/avg/bo_rf_wrap.yaml
  scripts/example_configs/femnist/avg/bohb.yaml
  scripts/example_configs/femnist/avg/bohb_wrap.yaml
Labels: bug, FedHPO-B

#336 [Feature] Add new system model
  benchmark/FedHPOB/README.md
  benchmark/FedHPOB/example.py
  benchmark/FedHPOB/fedhpob/benchmarks/base_benchmark.py
  benchmark/FedHPOB/fedhpob/benchmarks/raw_benchmark.py
  benchmark/FedHPOB/fedhpob/benchmarks/surrogate_benchmark.py
  benchmark/FedHPOB/fedhpob/benchmarks/tabular_benchmark.py
  benchmark/FedHPOB/fedhpob/config.py
  benchmark/FedHPOB/fedhpob/utils/cost_model.py
Labels: Feature, FedHPO-B

#302 support using cached data and re-splitting for huggingface datasets
  federatedscope/core/auxiliaries/data_builder.py
  federatedscope/nlp/baseline/fedavg_transformer_on_cola.yaml
  tests/test_vertical_fl.py
Labels: enhancement

#345 Remove redundant _ in expname
  federatedscope/core/auxiliaries/utils.py
Labels: bug

#347 Add prox and nbafl to README
  benchmark/FedHPOB/README.md
Labels: documentation, FedHPO-B

#324 [Feature] Add grid search to FedHPO-B
  benchmark/FedHPOB/fedhpob/config.py
  benchmark/FedHPOB/fedhpob/optimizers/__init__.py
  benchmark/FedHPOB/fedhpob/optimizers/grid_search.py
  benchmark/FedHPOB/fedhpob/utils/draw.py
  benchmark/FedHPOB/fedhpob/utils/runner.py
  benchmark/FedHPOB/scripts/exp/run_mode.sh
Labels: Feature, FedHPO-B

#350 Update paperlist
  materials/paper_list/Federated_Graph_Learning/README.md
Labels: documentation

#351 [Feature] Add parameters to control whether to check cfg
  federatedscope/autotune/fedex/client.py
  federatedscope/core/configs/config.py
Labels: Feature

#352 [hotfix] Fix var name
  federatedscope/gfl/gcflplus/worker.py
Labels: bug
