Repository alibaba/FederatedScope, pull requests merged in 2022-09, with the labels that each got.

#355 [Feature] Add color logging and move logging related utils to `logging`
  demo/bbo.py
  demo/hpbandster/rs.py
  demo/smac/gp.py
  demo/smac/rf.py
  demo/synthetic.py
  federatedscope/attack/auxiliary/utils.py
  federatedscope/attack/trainer/MIA_invert_gradient_trainer.py
  federatedscope/core/auxiliaries/logging.py
  federatedscope/core/auxiliaries/utils.py
  federatedscope/core/monitors/monitor.py
  federatedscope/hpo.py
  federatedscope/main.py
  run_reorganized_standalone.sh
  scripts/parse_exp_results_wandb.py
  tests/test_CRA_gan_attack.py
  tests/test_MIA_gradient_ascent.py
  tests/test_PIA_toy.py
  tests/test_asyn_cifar10.py
  tests/test_backdoor_attack.py
  tests/test_ditto.py
  tests/test_efficient_simulation.py
  tests/test_external_dataset.py
  tests/test_fedem.py
  tests/test_fedopt.py
  tests/test_fedprox.py
  tests/test_fedsageplus.py
  tests/test_femnist.py
  tests/test_finetune_lr.py
  tests/test_global_train_lr.py
  tests/test_graph_node_trainer.py
  tests/test_local_train_lr.py
  tests/test_mf.py
  tests/test_nbafl.py
  tests/test_optimizer.py
  tests/test_pfedme.py
  tests/test_rec_IG_opt_attack.py
  tests/test_rec_opt_attack.py
  tests/test_toy_lr.py
  tests/test_unseen_clients_lr.py
  tests/test_vertical_fl.py
Labels: enhancement

#358 bugfix for yaml dump due to the Argument class
  federatedscope/core/auxiliaries/logging.py
  federatedscope/core/configs/config.py
Labels: bug

#361 update news
  README.md
Labels: documentation

#362 Add KDD'22 tutorial material and news icon
  README.md
  materials/tutorial/KDD_2022/README.md
Labels: documentation

#370 Enable autotune to cikm
  federatedscope/autotune/algos.py
  federatedscope/core/monitors/monitor.py
  federatedscope/gfl/baseline/hpo_fedavg_gin_minibatch_on_cikmcup.yaml
  federatedscope/hpo.py
Labels: Feature

#374 Fix early_stop when the metric is the larger the better
  federatedscope/core/monitors/early_stopper.py
Labels: bug

#348 Support fairness related vector value in FedHPOB
  benchmark/FedHPOB/fedhpob/utils/tabular_dataloader.py
Labels: Feature, FedHPO-B

#372 add more registers & refactor splitter
  federatedscope/contrib/README.md
  federatedscope/contrib/__init__.py
  federatedscope/contrib/loss/__init__.py
  federatedscope/contrib/loss/example.py
  federatedscope/contrib/optimizer/__init__.py
  federatedscope/contrib/optimizer/example.py
  federatedscope/contrib/scheduler/__init__.py
  federatedscope/contrib/scheduler/example.py
  federatedscope/contrib/splitter/__init__.py
  federatedscope/contrib/splitter/example.py
  federatedscope/contrib/worker/__init__.py
  federatedscope/contrib/worker/example.py
  federatedscope/core/auxiliaries/criterion_builder.py
  federatedscope/core/auxiliaries/optimizer_builder.py
  federatedscope/core/auxiliaries/scheduler_builder.py
  federatedscope/core/auxiliaries/splitter_builder.py
  federatedscope/core/auxiliaries/worker_builder.py
  federatedscope/core/configs/README.md
  federatedscope/core/monitors/monitor.py
  federatedscope/core/splitters/__init__.py
  federatedscope/core/splitters/base_splitter.py
  federatedscope/core/splitters/generic/__init__.py
  federatedscope/core/splitters/generic/lda_splitter.py
  federatedscope/core/splitters/graph/__init__.py
  federatedscope/core/splitters/graph/graphtype_splitter.py
  federatedscope/core/splitters/graph/louvain_splitter.py
  federatedscope/core/splitters/graph/randchunk_splitter.py
  federatedscope/core/splitters/graph/random_splitter.py
  federatedscope/core/splitters/graph/reltype_splitter.py
  federatedscope/core/splitters/graph/scaffold_lda_splitter.py
  federatedscope/core/splitters/graph/scaffold_splitter.py
  federatedscope/gfl/baseline/repro_exp/graph_level/run_graph_level.sh
  federatedscope/gfl/baseline/repro_exp/graph_level/run_graph_level_opt.sh
  federatedscope/gfl/baseline/repro_exp/graph_level/run_graph_level_prox.sh
  federatedscope/nlp/loss/__init__.py
  federatedscope/nlp/model/__init__.py
  federatedscope/register.py
Labels: enhancement

#385 bugfix for merge_data
  federatedscope/core/auxiliaries/data_builder.py
Labels: bug

#381 Add HPOBench as backend demo for FedHPOBench
  benchmark/FedHPOBench/README.md
  benchmark/FedHPOBench/demo/__init__.py
  benchmark/FedHPOBench/demo/base_fed_surrogate_benchmark.py
  benchmark/FedHPOBench/demo/base_fed_tabular_benchmark.py
  benchmark/FedHPOBench/demo/femnist_surrogate_benchmark.py
  benchmark/FedHPOBench/demo/femnist_tabular_benchmark.py
  benchmark/FedHPOBench/example.py
  benchmark/FedHPOBench/fedhpobench/__init__.py
  benchmark/FedHPOBench/fedhpobench/benchmarks/__init__.py
  benchmark/FedHPOBench/fedhpobench/benchmarks/base_benchmark.py
  benchmark/FedHPOBench/fedhpobench/benchmarks/raw_benchmark.py
  benchmark/FedHPOBench/fedhpobench/benchmarks/surrogate_benchmark.py
  benchmark/FedHPOBench/fedhpobench/benchmarks/tabular_benchmark.py
  benchmark/FedHPOBench/fedhpobench/config.py
  benchmark/FedHPOBench/fedhpobench/optimizers/__init__.py
  benchmark/FedHPOBench/fedhpobench/optimizers/dehb_optimizer.py
  benchmark/FedHPOBench/fedhpobench/optimizers/grid_search.py
  benchmark/FedHPOBench/fedhpobench/optimizers/hpbandster_optimizer.py
  benchmark/FedHPOBench/fedhpobench/optimizers/optuna_optimizer.py
  benchmark/FedHPOBench/fedhpobench/optimizers/smac_optimizer.py
  benchmark/FedHPOBench/fedhpobench/utils/__init__.py
  benchmark/FedHPOBench/fedhpobench/utils/cost_model.py
  benchmark/FedHPOBench/fedhpobench/utils/draw.py
  benchmark/FedHPOBench/fedhpobench/utils/monitor.py
  benchmark/FedHPOBench/fedhpobench/utils/runner.py
  benchmark/FedHPOBench/fedhpobench/utils/surrogate_dataloader.py
  benchmark/FedHPOBench/fedhpobench/utils/tabular_dataloader.py
  benchmark/FedHPOBench/fedhpobench/utils/util.py
  benchmark/FedHPOBench/scripts/cnn/femnist_dp.yaml
  benchmark/FedHPOBench/scripts/cnn/run_hpo_dp_femnist_48.sh
Labels: enhancement, FedHPO-B

#387 minor fix and doc for cross backend fl
  federatedscope/core/auxiliaries/trainer_builder.py
  federatedscope/core/proto/gRPC_comm_manager_pb2_grpc.py
  federatedscope/core/workers/client.py
  federatedscope/core/workers/server.py
  federatedscope/cross_backends/README.md
  federatedscope/cross_backends/__init__.py
  federatedscope/cross_backends/distributed_tf_client_3.yaml
  federatedscope/cross_backends/distributed_tf_server.yaml
Labels: bug, documentation
