Repository alibaba/FederatedScope, pull requests merged in 2023-02, with the labels that each got.

#507 add several recent works on untargeted attacks in FL
  materials/paper_list/FL-Attacker/README.md
Labels: Materials

#510 Add gbdt
  federatedscope/core/auxiliaries/model_builder.py
  federatedscope/core/auxiliaries/worker_builder.py
  federatedscope/core/configs/cfg_fl_setting.py
  federatedscope/vertical_fl/loss/binary_cls.py
  federatedscope/vertical_fl/loss/regression.py
  federatedscope/vertical_fl/loss/utils.py
  federatedscope/vertical_fl/model/Tree.py
  federatedscope/vertical_fl/model/__init__.py
  federatedscope/vertical_fl/model/model_builder.py
  federatedscope/vertical_fl/trainer/trainer.py
  federatedscope/vertical_fl/utils.py
  federatedscope/vertical_fl/xgb_base/baseline/gbdt_base_on_adult.yaml
  federatedscope/vertical_fl/xgb_base/worker/evaluation_wrapper.py
  tests/test_xgb_and_gbdt.py
Labels: enhancement, Tree

#513 Minor fixes for GitHub workflow action and the mean/std values of DataTransforms
  .github/workflows/test_atc.yml
  federatedscope/core/configs/README.md
  federatedscope/core/configs/cfg_attack.py
  federatedscope/core/configs/cfg_data.py
  federatedscope/cv/baseline/fedavg_convnet2_on_celeba.yaml
  federatedscope/cv/baseline/fedavg_convnet2_on_cifar10.yaml
  federatedscope/cv/baseline/fedavg_convnet2_on_femnist.yaml
  federatedscope/cv/baseline/fedbn_convnet2_on_femnist.yaml
  materials/notebook/01_quick_start.ipynb
  materials/notebook/02_start_your_own_case.ipynb
  scripts/attack_exp_scripts/backdoor_attack/backdoor_badnet_fedavg_convnet2_on_femnist.yaml
  scripts/attack_exp_scripts/privacy_attack/CRA_fedavg_convnet2_on_femnist.yaml
  scripts/attack_exp_scripts/privacy_attack/gradient_ascent_MIA_on_femnist.yaml
  scripts/attack_exp_scripts/privacy_attack/gradient_ascent_MIA_on_femnist_simu_in.yaml
  scripts/attack_exp_scripts/privacy_attack/reconstruct_IG_fedavg_opt_on_femnist.yaml
  scripts/attack_exp_scripts/privacy_attack/reconstruct_fedavg_opt_on_femnist.yaml
  scripts/distributed_scripts/distributed_configs/distributed_femnist_client_1.yaml
  scripts/distributed_scripts/distributed_configs/distributed_femnist_client_2.yaml
  scripts/distributed_scripts/distributed_configs/distributed_femnist_client_3.yaml
  scripts/distributed_scripts/distributed_configs/distributed_femnist_server.yaml
  scripts/example_configs/asyn_cifar10.yaml
  scripts/example_configs/femnist.yaml
  scripts/example_configs/femnist_global_train.yaml
  scripts/personalization_exp_scripts/ditto/ditto_convnet2_on_femnist.yaml
  scripts/personalization_exp_scripts/fedbn/fedbn_convnet2_on_femnist.yaml
  scripts/personalization_exp_scripts/fedem/fedem_convnet2_on_femnist.yaml
  scripts/personalization_exp_scripts/pfedme/pfedme_convnet2_on_femnist.yaml
  tests/test_CRA_gan_attack.py
  tests/test_MIA_gradient_ascent.py
  tests/test_asyn_cifar10.py
  tests/test_backdoor_attack.py
  tests/test_ditto.py
  tests/test_external_dataset.py
  tests/test_fedem.py
  tests/test_fedopt.py
  tests/test_fedprox.py
  tests/test_femnist.py
  tests/test_nbafl.py
  tests/test_optimizer.py
  tests/test_pfedme.py
  tests/test_rec_IG_opt_attack.py
  tests/test_rec_opt_attack.py
  tests/test_trainer_property.py
Labels: enhancement

#521 update news
  README.md
Labels: documentation

#519 Add SWA
  federatedscope/core/configs/cfg_fl_algo.py
  federatedscope/core/configs/cfg_fl_setting.py
  federatedscope/core/data/base_data.py
  federatedscope/core/fed_runner.py
  federatedscope/core/workers/wrapper/__init__.py
  federatedscope/core/workers/wrapper/fedswa.py
  scripts/example_configs/fedswa.yaml
Labels: Feature

#522 Bind lager_better with each metric
  federatedscope/autotune/algos.py
  federatedscope/autotune/hpbandster.py
  federatedscope/autotune/smac.py
  federatedscope/autotune/utils.py
  federatedscope/core/configs/cfg_hpo.py
Labels: FedHPO

#509 pfedhpo and fts
  federatedscope/autotune/fts/__init__.py
  federatedscope/autotune/fts/client.py
  federatedscope/autotune/fts/server.py
  federatedscope/autotune/fts/utils.py
  federatedscope/autotune/pfedhpo/__init__.py
  federatedscope/autotune/pfedhpo/client.py
  federatedscope/autotune/pfedhpo/fl_server.py
  federatedscope/autotune/pfedhpo/server.py
  federatedscope/autotune/pfedhpo/utils.py
  federatedscope/core/auxiliaries/worker_builder.py
  federatedscope/core/configs/cfg_hpo.py
  scripts/example_configs/pfedhpo/cifar/pfedhpo.yaml
  scripts/example_configs/pfedhpo/cifar/run.sh
  scripts/example_configs/pfedhpo/cifar/ss.yaml
  scripts/example_configs/pfedhpo/mini_graph_dc/fedavg_per_client.yaml
  scripts/example_configs/pfedhpo/mini_graph_dc/pfedhpo.yaml
  scripts/example_configs/pfedhpo/mini_graph_dc/run.sh
  scripts/example_configs/pfedhpo/mini_graph_dc/ss.yaml
  scripts/example_configs/pfedhpo/twitter/pfedhpo.yaml
  scripts/example_configs/pfedhpo/twitter/run.sh
  scripts/example_configs/pfedhpo/twitter/ss.yaml
Labels: FedHPO

#528 label-based Tree model for vfl
  federatedscope/core/configs/cfg_fl_setting.py
  federatedscope/vertical_fl/trainer/__init__.py
  federatedscope/vertical_fl/trainer/feature_order_protected_trainer.py
  federatedscope/vertical_fl/trainer/label_protected_trainer.py
  federatedscope/vertical_fl/trainer/random_forest_trainer.py
  federatedscope/vertical_fl/trainer/trainer.py
  federatedscope/vertical_fl/trainer/utils.py
  federatedscope/vertical_fl/xgb_base/baseline/xgb_label_based_on_adult.yaml
  federatedscope/vertical_fl/xgb_base/worker/XGBClient.py
  federatedscope/vertical_fl/xgb_base/worker/evaluation_wrapper.py
  federatedscope/vertical_fl/xgb_base/worker/train_wrapper.py
  tests/test_tree_based_model_for_vfl.py
Labels: Feature, Tree

#529 Bugfix for tree based model
  federatedscope/vertical_fl/xgb_base/worker/train_wrapper.py
Labels: bug, Tree

#530 [bugfix] Add funcs to check empty subtree and remove the interaction between split position and activate indicator
  federatedscope/vertical_fl/model/Tree.py
  federatedscope/vertical_fl/trainer/label_protected_trainer.py
  federatedscope/vertical_fl/trainer/random_forest_trainer.py
  federatedscope/vertical_fl/trainer/trainer.py
Labels: bug, Tree

#533 Fix bucket size
  federatedscope/vertical_fl/trainer/feature_order_protected_trainer.py
  federatedscope/vertical_fl/trainer/label_protected_trainer.py
  federatedscope/vertical_fl/trainer/utils.py
Labels: bug, Tree
