Repository alibaba/FederatedScope, pull requests merged in 2023-03, with the labels that each got.

#536 Fix python version in dockerfile
  environment/docker_files/federatedscope-torch1.10-application.Dockerfile
  environment/docker_files/federatedscope-torch1.10.Dockerfile
  environment/docker_files/federatedscope-torch1.8-application.Dockerfile
Labels: bug

#487 Parallelization for standalone mode with NCCL
  federatedscope/autotune/utils.py
  federatedscope/core/auxiliaries/runner_builder.py
  federatedscope/core/communication.py
  federatedscope/core/configs/README.md
  federatedscope/core/configs/cfg_fl_setting.py
  federatedscope/core/configs/yacs_config.py
  federatedscope/core/fed_runner.py
  federatedscope/core/monitors/monitor.py
  federatedscope/core/parallel/README.md
  federatedscope/core/parallel/__init__.py
  federatedscope/core/parallel/parallel_runner.py
  federatedscope/core/trainers/context.py
  federatedscope/core/trainers/torch_trainer.py
  federatedscope/core/workers/client.py
  federatedscope/core/workers/server.py
Labels: enhancement

#541 Fix cost in demo
  benchmark/FedHPOBench/demo/base_fed_tabular_benchmark.py
  benchmark/FedHPOBench/demo/femnist_surrogate_benchmark.py
  benchmark/FedHPOBench/demo/femnist_tabular_benchmark.py
Labels: FedHPO

#546 Add serial num of msg
  federatedscope/core/fed_runner.py
  federatedscope/core/message.py
Labels: bug

#544 Optimize MF model
  federatedscope/core/auxiliaries/data_builder.py
  federatedscope/mf/baseline/hfl-sgdmf_fedavg_standalone_on_movielens1m.yaml
  federatedscope/mf/baseline/hfl_fedavg_standalone_on_movielens1m.yaml
  federatedscope/mf/baseline/hfl_fedavg_standalone_on_netflix.yaml
  federatedscope/mf/baseline/vfl-sgdmf_fedavg_standalone_on_movielens1m.yaml
  federatedscope/mf/baseline/vfl_fedavg_standalone_on_movielens1m.yaml
  federatedscope/mf/dataset/movielens.py
  federatedscope/mf/model/model.py
  federatedscope/mf/trainer/trainer.py
Labels: enhancement

#548 Fix synthetic data bug
  federatedscope/vertical_fl/dataloader/dataloader.py
Labels: bug

#550 bugfix
  federatedscope/vertical_fl/xgb_base/worker/train_wrapper.py
Labels: bug, Tree

#558 Load data from files
  .github/workflows/test_distribute.yml
  README.md
  federatedscope/contrib/data/load_from_files.py
  federatedscope/core/auxiliaries/data_builder.py
  federatedscope/core/auxiliaries/model_builder.py
  federatedscope/core/configs/README.md
  federatedscope/core/configs/cfg_data.py
  federatedscope/cross_backends/distributed_tf_client_3.yaml
  federatedscope/cross_backends/distributed_tf_server.yaml
  federatedscope/vertical_fl/dataloader/utils.py
  scripts/distributed_scripts/distributed_configs/distributed_client_1.yaml
  scripts/distributed_scripts/distributed_configs/distributed_client_2.yaml
  scripts/distributed_scripts/distributed_configs/distributed_client_3.yaml
  scripts/distributed_scripts/distributed_configs/distributed_server.yaml
  scripts/distributed_scripts/gen_data.py
  scripts/distributed_scripts/run_distributed_lr.sh
Labels: enhancement

#555 Compression methods
  .github/workflows/test_distribute.yml
  federatedscope/core/communication.py
  federatedscope/core/compression/README.md
  federatedscope/core/compression/__init__.py
  federatedscope/core/compression/utils.py
  federatedscope/core/configs/cfg_compression.py
  federatedscope/core/configs/cfg_fl_setting.py
  federatedscope/core/workers/client.py
  federatedscope/core/workers/server.py
  tests/test_femnist.py
Labels: Feature

#554 Add label-based version for RF
  federatedscope/vertical_fl/model/Tree.py
  federatedscope/vertical_fl/trainer/label_protected_trainer.py
  federatedscope/vertical_fl/trainer/trainer.py
  federatedscope/vertical_fl/xgb_base/baseline/rf_label_base_on_adult.yaml
  federatedscope/vertical_fl/xgb_base/baseline/xgb_label_base_on_abalone.yaml
  federatedscope/vertical_fl/xgb_base/worker/train_wrapper.py
  tests/test_tree_based_model_for_vfl.py
Labels: Feature, Tree

#559 Reconstruction for file paths and names in vertical_fl
  federatedscope/core/auxiliaries/model_builder.py
  federatedscope/core/auxiliaries/trainer_builder.py
  federatedscope/core/auxiliaries/worker_builder.py
  federatedscope/vertical_fl/linear_model/__init__.py
  federatedscope/vertical_fl/linear_model/baseline/vertical_fl.yaml
  federatedscope/vertical_fl/linear_model/baseline/vertical_on_adult.yaml
  federatedscope/vertical_fl/linear_model/worker/__init__.py
  federatedscope/vertical_fl/linear_model/worker/vertical_client.py
  federatedscope/vertical_fl/linear_model/worker/vertical_server.py
  federatedscope/vertical_fl/trainer/__init__.py
  federatedscope/vertical_fl/tree_based_models/__init__.py
  federatedscope/vertical_fl/tree_based_models/baseline/gbdt_base_on_abalone.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/gbdt_base_on_adult.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/gbdt_label_base_on_adult.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/rf_base_on_abalone.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/rf_base_on_adult.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/rf_label_base_on_adult.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_base_on_abalone.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_base_on_adult.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_base_on_adult_by_he_eval.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_base_on_blogfeedback.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_base_on_givemesomecredit.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_feature_order_dp_on_abalone.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_feature_order_dp_on_adult.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_feature_order_op_boost_on_adult.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_label_base_on_abalone.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_label_based_on_adult.yaml
  federatedscope/vertical_fl/tree_based_models/model/Tree.py
  federatedscope/vertical_fl/tree_based_models/model/__init__.py
  federatedscope/vertical_fl/tree_based_models/model/model_builder.py
  federatedscope/vertical_fl/tree_based_models/trainer/__init__.py
  federatedscope/vertical_fl/tree_based_models/trainer/feature_order_protected_trainer.py
  federatedscope/vertical_fl/tree_based_models/trainer/label_protected_trainer.py
  federatedscope/vertical_fl/tree_based_models/trainer/random_forest_trainer.py
  federatedscope/vertical_fl/tree_based_models/trainer/trainer.py
  federatedscope/vertical_fl/tree_based_models/trainer/utils.py
  federatedscope/vertical_fl/tree_based_models/worker/TreeClient.py
  federatedscope/vertical_fl/tree_based_models/worker/TreeServer.py
  federatedscope/vertical_fl/tree_based_models/worker/__init__.py
  federatedscope/vertical_fl/tree_based_models/worker/evaluation_wrapper.py
  federatedscope/vertical_fl/tree_based_models/worker/he_evaluation_wrapper.py
  federatedscope/vertical_fl/tree_based_models/worker/train_wrapper.py
  federatedscope/vertical_fl/utils.py
  federatedscope/vertical_fl/worker/__init__.py
  federatedscope/vertical_fl/xgb_base/worker/__init__.py
Labels: Tree

#560 Update paper list for FedNLP
  materials/paper_list/FL-NLP/README.md
Labels: documentation

#561 regular update for pFL paper list
  materials/paper_list/Personalized_FL/README.md
Labels: Materials

#563 Update README.md for installation
  README.md
Labels: documentation

#562 Rename models and add readme file
  federatedscope/core/configs/cfg_fl_setting.py
  federatedscope/vertical_fl/tree_based_models/baseline/README.md
  federatedscope/vertical_fl/tree_based_models/baseline/gbdt_feature_gathering_on_abalone.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/gbdt_feature_gathering_on_adult.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/gbdt_label_scattering_on_adult.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/rf_base_on_adult.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/rf_feature_gathering_on_abalone.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/rf_feature_gathering_on_adult.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/rf_label_scattering_on_adult.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_base_on_blogfeedback.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_feature_gathering_dp_on_abalone.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_feature_gathering_dp_on_adult.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_feature_gathering_on_abalone.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_feature_gathering_on_adult.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_feature_gathering_on_adult_by_he_eval.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_feature_gathering_op_boost_on_adult.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_label_scattering_on_abalone.yaml
  federatedscope/vertical_fl/tree_based_models/baseline/xgb_label_scattering_on_adult.yaml
  federatedscope/vertical_fl/tree_based_models/model/Tree.py
  federatedscope/vertical_fl/tree_based_models/trainer/label_protected_trainer.py
  federatedscope/vertical_fl/tree_based_models/trainer/trainer.py
  federatedscope/vertical_fl/tree_based_models/worker/TreeClient.py
  tests/test_tree_based_model_for_vfl.py
Labels: documentation
