Repository alibaba/FederatedScope, pull requests merged in 2023-04, with the labels that each got.

#565 update paper list: attack; fairness; incentive
  materials/paper_list/FL-Attacker/README.md
  materials/paper_list/FL-Fairness/README.md
  materials/paper_list/FL-Incentive/README.md
Labels: Materials

#556 Add README for tree-based models
  federatedscope/core/configs/cfg_fl_setting.py
  federatedscope/vertical_fl/README.md
Labels: documentation, Tree

#570 [DOC] Github actions for Auto API Ref
  .github/workflows/sphinx.yml
  doc/README.md
  doc/requirements-doc.txt
  doc/requirements.txt
Labels: documentation

#575 Update README.md for documentation
  README.md
Labels: skip-changelog

#577 add warning for NOT-FOUND metric
  federatedscope/core/auxiliaries/metric_builder.py
Labels: enhancement

#578 🚀🚀🚀 gRPC enhancement
  federatedscope/core/auxiliaries/utils.py
  federatedscope/core/message.py
  federatedscope/core/monitors/monitor.py
  federatedscope/core/trainers/tf_trainer.py
Labels: enhancement
